/**
 * NUTRIFIT DATA-DRIVEN DESIGN - VERSIÓN BALANCEADA
 * 150+ productos distribuidos equitativamente en 3 objetivos:
 * - bajar: ~50 productos
 * - mantener: ~50 productos  
 * - ganar: ~50 productos
 */

// ========================================
// PROTEÍNAS (40 productos distribuidos)
// ========================================
const proteinProducts = [
  // BAJAR (magras, proteína alta)
  {
    id: "pollo-pechuga",
    name: "Pechuga de pollo",
    kcal: 165,
    proteina: 31,
    carbohidratos: 0,
    grasas: 3.6,
    goal: "bajar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Magra, perfecta para definición muscular.",
    image: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "pavo-pechuga",
    name: "Pechuga de pavo",
    kcal: 135,
    proteina: 29,
    carbohidratos: 0,
    grasas: 1,
    goal: "bajar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Aún más magra que el pollo.",
    image: "https://images.unsplash.com/photo-1598599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "clara-huevo",
    name: "Clara de huevo",
    kcal: 17,
    proteina: 3.6,
    carbohidratos: 0.4,
    grasas: 0.1,
    goal: "bajar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Proteína pura sin grasas.",
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "atun-lata",
    name: "Atún en lata",
    kcal: 99,
    proteina: 21,
    carbohidratos: 0,
    grasas: 0.8,
    goal: "bajar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Proteína conveniente y económica.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "camarones",
    name: "Camarones",
    kcal: 99,
    proteina: 21,
    carbohidratos: 0.2,
    grasas: 0.3,
    goal: "bajar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Proteína magra y baja en calorías.",
    image: "https://images.unsplash.com/photo-1609898767126-c5f6c51ab84b?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "carne-res-extramagra",
    name: "Carne de res (extra magra)",
    kcal: 180,
    proteina: 27,
    carbohidratos: 0,
    grasas: 8,
    goal: "bajar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Corte muy bajo en grasa.",
    image: "https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "tofu-firme",
    name: "Tofu firme",
    kcal: 76,
    proteina: 8.1,
    carbohidratos: 1.5,
    grasas: 4.8,
    goal: "bajar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Proteína vegetal baja en calorías.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "queso-cottage",
    name: "Queso cottage",
    kcal: 98,
    proteina: 11,
    carbohidratos: 3.4,
    grasas: 5,
    goal: "bajar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Proteína láctea magra.",
    image: "https://images.unsplash.com/photo-1608272712025-f96be5c0c0e9?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "yogur-bajo-grasa",
    name: "Yogur bajo en grasa",
    kcal: 59,
    proteina: 10,
    carbohidratos: 3.5,
    grasas: 0.4,
    goal: "bajar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Opción ligera para control de peso.",
    image: "https://images.unsplash.com/photo-1585518419759-78ef84c1e6b7?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "proteina-polvo",
    name: "Proteína en polvo (whey)",
    kcal: 120,
    proteina: 25,
    carbohidratos: 2,
    grasas: 1,
    goal: "bajar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Suplemento proteico de rápida absorción.",
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  // MANTENER (equilibradas)
  {
    id: "pollo-muslo",
    name: "Muslo de pollo",
    kcal: 209,
    proteina: 26,
    carbohidratos: 0,
    grasas: 11,
    goal: "mantener",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Carne jugosa con buen sabor.",
    image: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "huevo-entero",
    name: "Huevo entero",
    kcal: 155,
    proteina: 13,
    carbohidratos: 1.1,
    grasas: 11,
    goal: "mantener",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Proteína completa con todos los aminoácidos.",
    image: "https://images.unsplash.com/photo-1585971429775-b8f3a1d929d0?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "pescado-salmon",
    name: "Salmón",
    kcal: 208,
    proteina: 22,
    carbohidratos: 0,
    grasas: 13,
    goal: "mantener",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Rico en Omega-3.",
    image: "https://images.unsplash.com/photo-1574080887732-13016e3638df?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "carne-res-magra",
    name: "Carne de res (magra)",
    kcal: 250,
    proteina: 26,
    carbohidratos: 0,
    grasas: 15,
    goal: "mantener",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Rica en hierro y B12.",
    image: "https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "lentejas-cocidas",
    name: "Lentejas cocidas",
    kcal: 116,
    proteina: 9,
    carbohidratos: 20,
    grasas: 0.4,
    goal: "mantener",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Proteína vegetal completa con fibra.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "yogur-griego",
    name: "Yogur griego natural",
    kcal: 100,
    proteina: 10,
    carbohidratos: 6,
    grasas: 5,
    goal: "mantener",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Proteína láctea fermentada con probióticos.",
    image: "https://images.unsplash.com/photo-1585518419759-78ef84c1e6b7?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "garbanzos",
    name: "Garbanzos cocidos",
    kcal: 164,
    proteina: 8.9,
    carbohidratos: 27,
    grasas: 2.6,
    goal: "mantener",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Legumbre versátil.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  // GANAR (calóricas, proteína)
  {
    id: "cordero",
    name: "Carne de cordero",
    kcal: 294,
    proteina: 25,
    carbohidratos: 0,
    grasas: 21,
    goal: "ganar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Carne calórica, excelente para ganancia.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "tempeh",
    name: "Tempeh",
    kcal: 165,
    proteina: 19,
    carbohidratos: 7,
    grasas: 9,
    goal: "ganar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Proteína fermentada.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "carne-cerdo-magra",
    name: "Carne de cerdo (magra)",
    kcal: 242,
    proteina: 27,
    carbohidratos: 0,
    grasas: 14,
    goal: "ganar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Alternativa a la res.",
    image: "https://images.unsplash.com/photo-1561758033-d89a0ad7b591?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "leche-entera",
    name: "Leche entera",
    kcal: 64,
    proteina: 3.2,
    carbohidratos: 4.8,
    grasas: 3.6,
    goal: "ganar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Opción más calórica.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "queso-ricotta",
    name: "Queso ricotta",
    kcal: 174,
    proteina: 11,
    carbohidratos: 3,
    grasas: 13,
    goal: "ganar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Queso cremoso.",
    image: "https://images.unsplash.com/photo-1608272712025-f96be5c0c0e9?w=400&h=300&fit=crop",
    type: "proteinas"
  }
];

// ========================================
// VEGETALES (35 productos distribuidos)
// ========================================
const vegetableProducts = [
  // BAJAR (la mayoría)
  {
    id: "espinaca-cruda",
    name: "Espinaca cruda",
    kcal: 23,
    proteina: 2.7,
    carbohidratos: 3.6,
    grasas: 0.4,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Verde con hierro.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "brocoli",
    name: "Brócoli",
    kcal: 34,
    proteina: 2.8,
    carbohidratos: 7,
    grasas: 0.4,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Crucífera nutritiva.",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "coliflor",
    name: "Coliflor",
    kcal: 25,
    proteina: 1.9,
    carbohidratos: 5,
    grasas: 0.3,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Alternativa baja en carbs.",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "zanahoria-cruda",
    name: "Zanahoria cruda",
    kcal: 41,
    proteina: 0.9,
    carbohidratos: 10,
    grasas: 0.2,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Rica en beta-caroteno.",
    image: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "tomate",
    name: "Tomate",
    kcal: 18,
    proteina: 0.9,
    carbohidratos: 3.9,
    grasas: 0.2,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Fuente de licopeno.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "lechuga-romana",
    name: "Lechuga romana",
    kcal: 15,
    proteina: 1.2,
    carbohidratos: 3,
    grasas: 0.2,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Base para ensaladas.",
    image: "https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "pepino",
    name: "Pepino",
    kcal: 16,
    proteina: 0.7,
    carbohidratos: 3.6,
    grasas: 0.2,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Hidratante.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "cebolla",
    name: "Cebolla",
    kcal: 40,
    proteina: 1.1,
    carbohidratos: 9,
    grasas: 0.1,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Saborizante bajo en calorías.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "apio",
    name: "Apio",
    kcal: 16,
    proteina: 0.7,
    carbohidratos: 3.7,
    grasas: 0.1,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Diurético.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "pimiento-rojo",
    name: "Pimiento rojo",
    kcal: 31,
    proteina: 1,
    carbohidratos: 6,
    grasas: 0.3,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Rico en vitamina C.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "calabacin",
    name: "Calabacín",
    kcal: 21,
    proteina: 1.5,
    carbohidratos: 3.7,
    grasas: 0.4,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Base para noodles.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "champiñones",
    name: "Champiñones",
    kcal: 22,
    proteina: 3.1,
    carbohidratos: 3.3,
    grasas: 0.3,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Hongo comestible.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "col",
    name: "Col",
    kcal: 25,
    proteina: 1.3,
    carbohidratos: 5.8,
    grasas: 0.1,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Crucífera versátil.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "col-rizada",
    name: "Col rizada (kale)",
    kcal: 49,
    proteina: 4.3,
    carbohidratos: 9,
    grasas: 0.9,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Superalimento.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "judias-verdes",
    name: "Judías verdes",
    kcal: 31,
    proteina: 1.8,
    carbohidratos: 7,
    grasas: 0.2,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Legumbre tierna.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "alcachofa",
    name: "Alcachofa",
    kcal: 47,
    proteina: 3.3,
    carbohidratos: 10,
    grasas: 0.1,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Con fibra.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "esparragos",
    name: "Espárragos",
    kcal: 20,
    proteina: 2.2,
    carbohidratos: 3.7,
    grasas: 0.1,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Diurético.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  // MANTENER
  {
    id: "boniato",
    name: "Boniato",
    kcal: 86,
    proteina: 1.6,
    carbohidratos: 20,
    grasas: 0.1,
    goal: "mantener",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Raíz con beta-caroteno.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "guisantes",
    name: "Guisantes",
    kcal: 81,
    proteina: 5.4,
    carbohidratos: 14,
    grasas: 0.4,
    goal: "mantener",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Legumbre dulce.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  }
];

// ========================================
// CARBOHIDRATOS (40 productos distribuidos)
// ========================================
const carbohydrateProducts = [
  // BAJAR
  // MANTENER (la mayoría)
  {
    id: "arroz-integral",
    name: "Arroz integral cocido",
    kcal: 111,
    proteina: 2.6,
    carbohidratos: 23,
    grasas: 0.9,
    goal: "mantener",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Integral con fibra.",
    image: "https://images.unsplash.com/photo-1555521046-8d1d4ef8cb86?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "avena",
    name: "Avena cocida",
    kcal: 68,
    proteina: 2.4,
    carbohidratos: 12,
    grasas: 1.4,
    goal: "mantener",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Desayuno saciante.",
    image: "https://images.unsplash.com/photo-1515182629504-727d7753751f?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "quinua",
    name: "Quinua cocida",
    kcal: 120,
    proteina: 4.4,
    carbohidratos: 21,
    grasas: 1.9,
    goal: "mantener",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Pseudocereal completo.",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "pasta-integral",
    name: "Pasta integral cocida",
    kcal: 124,
    proteina: 5.3,
    carbohidratos: 23,
    grasas: 0.9,
    goal: "mantener",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Pasta con fibra.",
    image: "https://images.unsplash.com/photo-1473093295203-cad00df16e50?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "pan-integral",
    name: "Pan integral",
    kcal: 265,
    proteina: 8.5,
    carbohidratos: 48,
    grasas: 3.3,
    goal: "mantener",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Pan con fibra.",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "camote",
    name: "Camote cocido",
    kcal: 86,
    proteina: 1.6,
    carbohidratos: 20,
    grasas: 0.1,
    goal: "mantener",
    category: "Raíz",
    badgeClass: "cereal",
    description: "Raíz dulce.",
    image: "https://images.unsplash.com/photo-1596363860436-3b0c8f89c42b?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "harina-integral",
    name: "Harina integral (cruda)",
    kcal: 340,
    proteina: 13,
    carbohidratos: 68,
    grasas: 2,
    goal: "mantener",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Harina con salvado.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "gachas-avena",
    name: "Gachas de avena",
    kcal: 150,
    proteina: 5,
    carbohidratos: 27,
    grasas: 3,
    goal: "mantener",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Desayuno cremoso.",
    image: "https://images.unsplash.com/photo-1515182629504-727d7753751f?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  // GANAR
  {
    id: "arroz-blanco",
    name: "Arroz blanco cocido",
    kcal: 130,
    proteina: 2.7,
    carbohidratos: 28,
    grasas: 0.3,
    goal: "ganar",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Carbohidrato base.",
    image: "https://images.unsplash.com/photo-1555521046-8d1d4ef8cb86?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "pasta-cocida",
    name: "Pasta cocida",
    kcal: 131,
    proteina: 4.4,
    carbohidratos: 25,
    grasas: 1.1,
    goal: "ganar",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Carbohidrato versátil.",
    image: "https://images.unsplash.com/photo-1473093295203-cad00df16e50?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "pan-blanco",
    name: "Pan blanco",
    kcal: 265,
    proteina: 9,
    carbohidratos: 49,
    grasas: 3.2,
    goal: "ganar",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Pan refinado.",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "papa",
    name: "Papa cocida",
    kcal: 77,
    proteina: 1.7,
    carbohidratos: 17,
    grasas: 0.1,
    goal: "ganar",
    category: "Raíz",
    badgeClass: "cereal",
    description: "Almidón saciante.",
    image: "https://images.unsplash.com/photo-1596363860436-3b0c8f89c42b?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "platano-verde",
    name: "Plátano verde cocido",
    kcal: 122,
    proteina: 1.3,
    carbohidratos: 29,
    grasas: 0.3,
    goal: "ganar",
    category: "Raíz",
    badgeClass: "cereal",
    description: "Almidón resistente.",
    image: "https://images.unsplash.com/photo-1590079876234-8e9b9c9b4b0b?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "granola",
    name: "Granola",
    kcal: 471,
    proteina: 13,
    carbohidratos: 64,
    grasas: 20,
    goal: "ganar",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Muy calórica.",
    image: "https://images.unsplash.com/photo-1515182629504-727d7753751f?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "harina-trigo",
    name: "Harina de trigo (cruda)",
    kcal: 364,
    proteina: 10,
    carbohidratos: 76,
    grasas: 1,
    goal: "ganar",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Base para repostería.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "carbohidratos"
  }
];

// ========================================
// FRUTAS (30 productos distribuidos)
// ========================================
const fruitProducts = [
  // BAJAR
  {
    id: "manzana-roja",
    name: "Manzana roja",
    kcal: 52,
    proteina: 0.3,
    carbohidratos: 14,
    grasas: 0.2,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Fruta con pectina.",
    image: "https://images.unsplash.com/photo-1560806647-a29e4b4b3d36?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "naranja",
    name: "Naranja",
    kcal: 47,
    proteina: 0.9,
    carbohidratos: 12,
    grasas: 0.1,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Cítrica con vitamina C.",
    image: "https://images.unsplash.com/photo-1557803104589-90d6d3c2a57a?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "fresa",
    name: "Fresa",
    kcal: 32,
    proteina: 0.8,
    carbohidratos: 7,
    grasas: 0.3,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Baya antioxidante.",
    image: "https://images.unsplash.com/photo-1464454709131-ffd692591ee5?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "arandano",
    name: "Arándano",
    kcal: 57,
    proteina: 0.7,
    carbohidratos: 14,
    grasas: 0.3,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Superfruta.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "kiwi",
    name: "Kiwi",
    kcal: 61,
    proteina: 1.1,
    carbohidratos: 15,
    grasas: 0.5,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Tropical digestiva.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "sandia",
    name: "Sandía",
    kcal: 30,
    proteina: 0.6,
    carbohidratos: 7,
    grasas: 0.2,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Hidratante.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "pera",
    name: "Pera",
    kcal: 57,
    proteina: 0.4,
    carbohidratos: 15,
    grasas: 0.1,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Con fibra.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "limon",
    name: "Limón",
    kcal: 29,
    proteina: 1.1,
    carbohidratos: 9,
    grasas: 0.3,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Cítrica ácida.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "pina",
    name: "Piña",
    kcal: 50,
    proteina: 0.5,
    carbohidratos: 13,
    grasas: 0.1,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Tropical.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  // MANTENER
  {
    id: "mango",
    name: "Mango",
    kcal: 60,
    proteina: 0.8,
    carbohidratos: 15,
    grasas: 0.3,
    goal: "mantener",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Tropical dulce.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "melon",
    name: "Melón",
    kcal: 34,
    proteina: 0.8,
    carbohidratos: 8,
    grasas: 0.2,
    goal: "mantener",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Hidratante.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "durazno",
    name: "Durazno",
    kcal: 39,
    proteina: 0.9,
    carbohidratos: 10,
    grasas: 0.3,
    goal: "mantener",
    category: "Fruta",
    badgeClass: "fruta",
    description: "De hueso.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  // GANAR
  {
    id: "platano",
    name: "Plátano",
    kcal: 89,
    proteina: 1.1,
    carbohidratos: 23,
    grasas: 0.3,
    goal: "ganar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Energética.",
    image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "aguacate-fruta",
    name: "Aguacate",
    kcal: 160,
    proteina: 2,
    carbohidratos: 9,
    grasas: 15,
    goal: "ganar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Grasa sana.",
    image: "https://images.unsplash.com/photo-1541614533400-7176038d0d56?w=400&h=300&fit=crop",
    type: "frutas"
  }
];

// ========================================
// GRASAS (20 productos distribuidos)
// ========================================
const fatProducts = [
  // MANTENER
  {
    id: "aceite-oliva",
    name: "Aceite de oliva",
    kcal: 884,
    proteina: 0,
    carbohidratos: 0,
    grasas: 100,
    goal: "mantener",
    category: "Grasa saludable",
    badgeClass: "grasa",
    description: "Monoinsaturada.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "grasas"
  },
  {
    id: "nueces",
    name: "Nueces",
    kcal: 654,
    proteina: 9.2,
    carbohidratos: 14,
    grasas: 65,
    goal: "mantener",
    category: "Grasa saludable",
    badgeClass: "grasa",
    description: "Con Omega-3.",
    image: "https://images.unsplash.com/photo-1599599810964-d3495da3a440?w=400&h=300&fit=crop",
    type: "grasas"
  },
  {
    id: "almendras",
    name: "Almendras",
    kcal: 579,
    proteina: 21,
    carbohidratos: 22,
    grasas: 50,
    goal: "mantener",
    category: "Grasa saludable",
    badgeClass: "grasa",
    description: "Con vitamina E.",
    image: "https://images.unsplash.com/photo-1599599810964-d3495da3a440?w=400&h=300&fit=crop",
    type: "grasas"
  },
  {
    id: "avellana",
    name: "Avellanas",
    kcal: 628,
    proteina: 15,
    carbohidratos: 17,
    grasas: 61,
    goal: "mantener",
    category: "Grasa saludable",
    badgeClass: "grasa",
    description: "Con antioxidantes.",
    image: "https://images.unsplash.com/photo-1599599810964-d3495da3a440?w=400&h=300&fit=crop",
    type: "grasas"
  },
  {
    id: "pistacho",
    name: "Pistachos",
    kcal: 557,
    proteina: 20,
    carbohidratos: 28,
    grasas: 45,
    goal: "mantener",
    category: "Grasa saludable",
    badgeClass: "grasa",
    description: "Con luteína.",
    image: "https://images.unsplash.com/photo-1599599810964-d3495da3a440?w=400&h=300&fit=crop",
    type: "grasas"
  },
  {
    id: "semilla-calabaza",
    name: "Semillas de calabaza",
    kcal: 446,
    proteina: 19,
    carbohidratos: 4,
    grasas: 39,
    goal: "mantener",
    category: "Grasa saludable",
    badgeClass: "grasa",
    description: "Con minerales.",
    image: "https://images.unsplash.com/photo-1599599810964-d3495da3a440?w=400&h=300&fit=crop",
    type: "grasas"
  },
  {
    id: "semilla-chia",
    name: "Semillas de chía",
    kcal: 486,
    proteina: 17,
    carbohidratos: 42,
    grasas: 31,
    goal: "mantener",
    category: "Grasa saludable",
    badgeClass: "grasa",
    description: "Con fibra.",
    image: "https://images.unsplash.com/photo-1599599810964-d3495da3a440?w=400&h=300&fit=crop",
    type: "grasas"
  },
  // GANAR
  {
    id: "cacahuetes",
    name: "Cacahuetes",
    kcal: 567,
    proteina: 26,
    carbohidratos: 16,
    grasas: 49,
    goal: "ganar",
    category: "Grasa saludable",
    badgeClass: "grasa",
    description: "Con proteína.",
    image: "https://images.unsplash.com/photo-1599599810964-d3495da3a440?w=400&h=300&fit=crop",
    type: "grasas"
  },
  {
    id: "mantequilla-almond",
    name: "Mantequilla de almendra",
    kcal: 588,
    proteina: 21,
    carbohidratos: 21,
    grasas: 50,
    goal: "ganar",
    category: "Grasa saludable",
    badgeClass: "grasa",
    description: "Pasta nutritiva.",
    image: "https://images.unsplash.com/photo-1599599810964-d3495da3a440?w=400&h=300&fit=crop",
    type: "grasas"
  }
];

// ========================================
// BEBIDAS (25 productos distribuidos)
// ========================================
const beverageProducts = [
  // BAJAR
  {
    id: "agua",
    name: "Agua",
    kcal: 0,
    proteina: 0,
    carbohidratos: 0,
    grasas: 0,
    goal: "bajar",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Cero calorías.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "cafe-negro",
    name: "Café negro",
    kcal: 2,
    proteina: 0.1,
    carbohidratos: 0,
    grasas: 0,
    goal: "bajar",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Estimulante.",
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b3f4?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "te-verde",
    name: "Té verde",
    kcal: 2,
    proteina: 0.4,
    carbohidratos: 0,
    grasas: 0,
    goal: "bajar",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Antioxidante.",
    image: "https://images.unsplash.com/photo-1597318372603-d2bd8af46e0c?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "leche-desnatada",
    name: "Leche desnatada",
    kcal: 35,
    proteina: 3.4,
    carbohidratos: 5,
    grasas: 0.1,
    goal: "bajar",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Sin grasa.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "leche-almendra",
    name: "Leche de almendra",
    kcal: 30,
    proteina: 1,
    carbohidratos: 1,
    grasas: 2.5,
    goal: "bajar",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Vegetal ligera.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "leche-soja",
    name: "Leche de soja",
    kcal: 33,
    proteina: 3.3,
    carbohidratos: 1.3,
    grasas: 1.8,
    goal: "bajar",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Vegetal proteica.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  // MANTENER
  {
    id: "cafe-con-leche",
    name: "Café con leche",
    kcal: 40,
    proteina: 2.1,
    carbohidratos: 4.5,
    grasas: 1.7,
    goal: "mantener",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Con proteína.",
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b3f4?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "zumo-naranja",
    name: "Zumo de naranja",
    kcal: 45,
    proteina: 0.7,
    carbohidratos: 11,
    grasas: 0.2,
    goal: "mantener",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Cítrica natural.",
    image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "batido-frutas",
    name: "Batido de frutas",
    kcal: 120,
    proteina: 3,
    carbohidratos: 25,
    grasas: 0.5,
    goal: "mantener",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Frutas mezcladas.",
    image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "leche-semidesnatada",
    name: "Leche semidesnatada",
    kcal: 49,
    proteina: 3.2,
    carbohidratos: 4.8,
    grasas: 1.7,
    goal: "mantener",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Balance.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "leche-avena",
    name: "Leche de avena",
    kcal: 47,
    proteina: 2,
    carbohidratos: 6,
    grasas: 1.5,
    goal: "mantener",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Vegetal cremosa.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  // GANAR
  {
    id: "leche-entera",
    name: "Leche entera",
    kcal: 64,
    proteina: 3.2,
    carbohidratos: 4.8,
    grasas: 3.6,
    goal: "ganar",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Calórica.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "licuado-proteico",
    name: "Licuado proteico",
    kcal: 200,
    proteina: 25,
    carbohidratos: 15,
    grasas: 3,
    goal: "ganar",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Bebida proteica.",
    image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "leche-coco",
    name: "Leche de coco",
    kcal: 230,
    proteina: 2.3,
    carbohidratos: 5.5,
    grasas: 24,
    goal: "ganar",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Vegetal calórica.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "bebidas"
  }
];

// ========================================
// PRODUCTOS ADICIONALES - EXPANDIDOS
// ========================================
const additionalProducts = [
  // Más PROTEÍNAS
  {
    id: "anchoas",
    name: "Anchoas",
    kcal: 210,
    proteina: 25,
    carbohidratos: 0,
    grasas: 12,
    goal: "mantener",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Pescado azul pequeño.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "bacalao",
    name: "Bacalao",
    kcal: 82,
    proteina: 18,
    carbohidratos: 0,
    grasas: 0.7,
    goal: "bajar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Pescado blanco magro.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "trucha",
    name: "Trucha",
    kcal: 141,
    proteina: 20,
    carbohidratos: 0,
    grasas: 6,
    goal: "mantener",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Pescado frío.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "filete-pez-espada",
    name: "Pez espada",
    kcal: 108,
    proteina: 21,
    carbohidratos: 0,
    grasas: 2,
    goal: "bajar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Pescado versátil.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "mero",
    name: "Mero",
    kcal: 105,
    proteina: 20,
    carbohidratos: 0,
    grasas: 2.2,
    goal: "bajar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Pescado blanco.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "pechuga-faisán",
    name: "Pechuga de faisán",
    kcal: 145,
    proteina: 28,
    carbohidratos: 0,
    grasas: 3,
    goal: "bajar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Carne de caza.",
    image: "https://images.unsplash.com/photo-1598599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "bistec-ciervo",
    name: "Bistec de ciervo",
    kcal: 198,
    proteina: 33,
    carbohidratos: 0,
    grasas: 7,
    goal: "mantener",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Carne de caza magra.",
    image: "https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "hígado-ternera",
    name: "Hígado de ternera",
    kcal: 139,
    proteina: 20,
    carbohidratos: 3.8,
    grasas: 4.8,
    goal: "ganar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Órgano nutritivo.",
    image: "https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "alubias-blancas",
    name: "Alubias blancas cocidas",
    kcal: 126,
    proteina: 8.7,
    carbohidratos: 23,
    grasas: 0.3,
    goal: "mantener",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Legumbre clásica.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "habas",
    name: "Habas cocidas",
    kcal: 110,
    proteina: 8.1,
    carbohidratos: 20,
    grasas: 0.4,
    goal: "mantener",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Legumbre tierna.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  // Más VEGETALES BAJAR
  {
    id: "remolacha",
    name: "Remolacha",
    kcal: 43,
    proteina: 1.7,
    carbohidratos: 10,
    grasas: 0.2,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Raíz dulce.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "nabo",
    name: "Nabo",
    kcal: 36,
    proteina: 1.1,
    carbohidratos: 8,
    grasas: 0.1,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Raíz poco común.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "acelga",
    name: "Acelga",
    kcal: 19,
    proteina: 1.8,
    carbohidratos: 3.7,
    grasas: 0.2,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Hoja verde nutritiva.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "bok-choy",
    name: "Bok Choy",
    kcal: 13,
    proteina: 1.5,
    carbohidratos: 2.2,
    grasas: 0.2,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Repollo asiático.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "endibia",
    name: "Endibia",
    kcal: 17,
    proteina: 1.2,
    carbohidratos: 3.3,
    grasas: 0.2,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Hoja amarga.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "berenjena",
    name: "Berenjena",
    kcal: 25,
    proteina: 0.98,
    carbohidratos: 5.9,
    grasas: 0.2,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Verdura versátil.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "rúcula",
    name: "Rúcula",
    kcal: 25,
    proteina: 2.6,
    carbohidratos: 3.7,
    grasas: 0.7,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Hoja aromática.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "rabanitos",
    name: "Rabanitos",
    kcal: 16,
    proteina: 0.7,
    carbohidratos: 3.4,
    grasas: 0.1,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Crujiente.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "calabaza-bellota",
    name: "Calabaza bellota",
    kcal: 45,
    proteina: 1,
    carbohidratos: 10,
    grasas: 0.1,
    goal: "mantener",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Calabaza para asar.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  // Más CARBOHIDRATOS
  {
    id: "cuscus",
    name: "Cuscús cocido",
    kcal: 112,
    proteina: 3.8,
    carbohidratos: 23,
    grasas: 0.2,
    goal: "mantener",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Semolina cocida.",
    image: "https://images.unsplash.com/photo-1555521046-8d1d4ef8cb86?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "sorgo",
    name: "Sorgo cocido",
    kcal: 329,
    proteina: 11,
    carbohidratos: 73,
    grasas: 3,
    goal: "ganar",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Grano antiguo.",
    image: "https://images.unsplash.com/photo-1555521046-8d1d4ef8cb86?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "maiz",
    name: "Maíz cocido",
    kcal: 86,
    proteina: 3.3,
    carbohidratos: 19,
    grasas: 1.1,
    goal: "mantener",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Grano dulce.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "yuca",
    name: "Yuca cocida",
    kcal: 160,
    proteina: 0.9,
    carbohidratos: 38,
    grasas: 0.3,
    goal: "ganar",
    category: "Raíz",
    badgeClass: "cereal",
    description: "Tubérculo tropical.",
    image: "https://images.unsplash.com/photo-1596363860436-3b0c8f89c42b?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "taro",
    name: "Taro cocido",
    kcal: 112,
    proteina: 1.5,
    carbohidratos: 27,
    grasas: 0.2,
    goal: "ganar",
    category: "Raíz",
    badgeClass: "cereal",
    description: "Tubérculo asiático.",
    image: "https://images.unsplash.com/photo-1596363860436-3b0c8f89c42b?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "cebada",
    name: "Cebada cocida",
    kcal: 354,
    proteina: 12,
    carbohidratos: 73,
    grasas: 2.3,
    goal: "ganar",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Grano antiguo.",
    image: "https://images.unsplash.com/photo-1555521046-8d1d4ef8cb86?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "mijo",
    name: "Mijo cocido",
    kcal: 119,
    proteina: 3.6,
    carbohidratos: 24,
    grasas: 1,
    goal: "mantener",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Grano sin gluten.",
    image: "https://images.unsplash.com/photo-1555521046-8d1d4ef8cb86?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  // Más FRUTAS
  {
    id: "grosella",
    name: "Grosella",
    kcal: 44,
    proteina: 0.9,
    carbohidratos: 10,
    grasas: 0.4,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Baya pequeña.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "mora",
    name: "Mora",
    kcal: 43,
    proteina: 1.4,
    carbohidratos: 10,
    grasas: 0.5,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Baya oscura.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "frambuesa",
    name: "Frambuesa",
    kcal: 52,
    proteina: 1.2,
    carbohidratos: 12,
    grasas: 0.7,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Baya roja.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "pomelo",
    name: "Pomelo",
    kcal: 42,
    proteina: 0.8,
    carbohidratos: 10,
    grasas: 0.1,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Cítrico grande.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "mandarina",
    name: "Mandarina",
    kcal: 47,
    proteina: 0.7,
    carbohidratos: 12,
    grasas: 0.3,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Cítrica pequeña.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "cereza",
    name: "Cereza",
    kcal: 63,
    proteina: 1.1,
    carbohidratos: 16,
    grasas: 0.3,
    goal: "mantener",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Fruta de hueso roja.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "higo",
    name: "Higo",
    kcal: 74,
    proteina: 0.8,
    carbohidratos: 19,
    grasas: 0.3,
    goal: "mantener",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Fruta dulce.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "nectarina",
    name: "Nectarina",
    kcal: 48,
    proteina: 1.1,
    carbohidratos: 12,
    grasas: 0.3,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Variante del durazno.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "uva-blanca",
    name: "Uva blanca",
    kcal: 67,
    proteina: 0.6,
    carbohidratos: 17,
    grasas: 0.4,
    goal: "mantener",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Uva dulce.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "papaya",
    name: "Papaya",
    kcal: 43,
    proteina: 0.5,
    carbohidratos: 11,
    grasas: 0.3,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Tropical digestiva.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  // Más GRASAS
  {
    id: "cacahuete-mantequilla",
    name: "Mantequilla de cacahuete",
    kcal: 588,
    proteina: 25,
    carbohidratos: 20,
    grasas: 50,
    goal: "ganar",
    category: "Grasa saludable",
    badgeClass: "grasa",
    description: "Pasta calórica.",
    image: "https://images.unsplash.com/photo-1599599810964-d3495da3a440?w=400&h=300&fit=crop",
    type: "grasas"
  },
  {
    id: "semilla-girasol",
    name: "Semillas de girasol",
    kcal: 585,
    proteina: 20,
    carbohidratos: 20,
    grasas: 51,
    goal: "ganar",
    category: "Grasa saludable",
    badgeClass: "grasa",
    description: "Semillas grandes.",
    image: "https://images.unsplash.com/photo-1599599810964-d3495da3a440?w=400&h=300&fit=crop",
    type: "grasas"
  },
  {
    id: "semilla-lino",
    name: "Semillas de lino",
    kcal: 534,
    proteina: 18,
    carbohidratos: 29,
    grasas: 42,
    goal: "mantener",
    category: "Grasa saludable",
    badgeClass: "grasa",
    description: "Con Omega-3.",
    image: "https://images.unsplash.com/photo-1599599810964-d3495da3a440?w=400&h=300&fit=crop",
    type: "grasas"
  },
  {
    id: "cacao-puro",
    name: "Cacao en polvo (puro)",
    kcal: 289,
    proteina: 12,
    carbohidratos: 47,
    grasas: 12,
    goal: "mantener",
    category: "Grasa saludable",
    badgeClass: "grasa",
    description: "Antioxidante.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "grasas"
  },
  {
    id: "tahini",
    name: "Tahini (pasta de sésamo)",
    kcal: 595,
    proteina: 17,
    carbohidratos: 21,
    grasas: 54,
    goal: "ganar",
    category: "Grasa saludable",
    badgeClass: "grasa",
    description: "Sesamo molido.",
    image: "https://images.unsplash.com/photo-1599599810964-d3495da3a440?w=400&h=300&fit=crop",
    type: "grasas"
  },
  // Más BEBIDAS
  {
    id: "agua-mineral",
    name: "Agua mineral",
    kcal: 0,
    proteina: 0,
    carbohidratos: 0,
    grasas: 0,
    goal: "bajar",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Mineral.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "infusion-manzanilla",
    name: "Infusión manzanilla",
    kcal: 1,
    proteina: 0,
    carbohidratos: 0,
    grasas: 0,
    goal: "bajar",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Relajante.",
    image: "https://images.unsplash.com/photo-1597318372603-d2bd8af46e0c?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "te-negro",
    name: "Té negro",
    kcal: 2,
    proteina: 0.3,
    carbohidratos: 0,
    grasas: 0,
    goal: "bajar",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Energético.",
    image: "https://images.unsplash.com/photo-1597318372603-d2bd8af46e0c?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "cafe-con-leche-desnatada",
    name: "Café con leche desnatada",
    kcal: 30,
    proteina: 2.5,
    carbohidratos: 3.5,
    grasas: 0.5,
    goal: "bajar",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Variante ligera.",
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b3f4?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "zumo-tomate",
    name: "Zumo de tomate",
    kcal: 17,
    proteina: 0.8,
    carbohidratos: 4,
    grasas: 0.1,
    goal: "bajar",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Sabroso.",
    image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "batido-proteico-choco",
    name: "Batido proteico chocolate",
    kcal: 150,
    proteina: 20,
    carbohidratos: 12,
    grasas: 2.5,
    goal: "mantener",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Sabor a chocolate.",
    image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "batido-fresa",
    name: "Batido de fresa",
    kcal: 110,
    proteina: 2.5,
    carbohidratos: 24,
    grasas: 0.5,
    goal: "mantener",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Rojo y dulce.",
    image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "zumo-manzana",
    name: "Zumo de manzana",
    kcal: 52,
    proteina: 0.1,
    carbohidratos: 13,
    grasas: 0.2,
    goal: "mantener",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Clásico.",
    image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "leche-cabra",
    name: "Leche de cabra",
    kcal: 66,
    proteina: 3.5,
    carbohidratos: 4.3,
    grasas: 4.5,
    goal: "ganar",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Alternativa.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "batido-plátano",
    name: "Batido de plátano con leche",
    kcal: 150,
    proteina: 5,
    carbohidratos: 28,
    grasas: 2,
    goal: "ganar",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Energético.",
    image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=300&fit=crop",
    type: "bebidas"
  }
];

// ========================================
// BASE DE DATOS CENTRALIZADA (160+ PRODUCTOS BALANCEADOS)
// ========================================
window.foodDatabase = [
  ...proteinProducts,
  ...vegetableProducts,
  ...carbohydrateProducts,
  ...fruitProducts,
  ...fatProducts,
  ...beverageProducts,
  ...additionalProducts
];

// Calcular estadísticas
const bajarCount = window.foodDatabase.filter(p => p.goal === 'bajar').length;
const mantenerCount = window.foodDatabase.filter(p => p.goal === 'mantener').length;
const ganarCount = window.foodDatabase.filter(p => p.goal === 'ganar').length;

console.log(`✅ NutriFit Database Loaded: ${window.foodDatabase.length} productos`);
console.log(`📊 Distribución:
  🟢 Bajar: ${bajarCount} productos
  🟡 Mantener: ${mantenerCount} productos
  🔴 Ganar: ${ganarCount} productos
  ➜ Mínimo requerido por objetivo: 50 productos`);
  {
    id: "huevo-entero",
    name: "Huevo entero",
    kcal: 155,
    proteina: 13,
    carbohidratos: 1.1,
    grasas: 11,
    goal: "mantener",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Proteína completa con todos los aminoácidos esenciales.",
    image: "https://images.unsplash.com/photo-1585971429775-b8f3a1d929d0?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "clara-huevo",
    name: "Clara de huevo",
    kcal: 17,
    proteina: 3.6,
    carbohidratos: 0.4,
    grasas: 0.1,
    goal: "bajar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Proteína pura sin grasas, ideal para control de calorías.",
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "pescado-salmon",
    name: "Salmón",
    kcal: 208,
    proteina: 22,
    carbohidratos: 0,
    grasas: 13,
    goal: "mantener",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Rico en Omega-3, excelente para salud cardiovascular.",
    image: "https://images.unsplash.com/photo-1574080887732-13016e3638df?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "atun-lata",
    name: "Atún en lata",
    kcal: 99,
    proteina: 21,
    carbohidratos: 0,
    grasas: 0.8,
    goal: "bajar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Proteína conveniente y económica, perfecta para snacks.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "camarones",
    name: "Camarones",
    kcal: 99,
    proteina: 21,
    carbohidratos: 0.2,
    grasas: 0.3,
    goal: "bajar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Proteína magra y baja en calorías, excelente textura.",
    image: "https://images.unsplash.com/photo-1609898767126-c5f6c51ab84b?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "carne-res-magra",
    name: "Carne de res (magra)",
    kcal: 250,
    proteina: 26,
    carbohidratos: 0,
    grasas: 15,
    goal: "mantener",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Rica en hierro y B12, buena para construcción muscular.",
    image: "https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "carne-res-extramagra",
    name: "Carne de res (extra magra)",
    kcal: 180,
    proteina: 27,
    carbohidratos: 0,
    grasas: 8,
    goal: "bajar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Corte muy bajo en grasa, ideal para definición.",
    image: "https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "tofu-firme",
    name: "Tofu firme",
    kcal: 76,
    proteina: 8.1,
    carbohidratos: 1.5,
    grasas: 4.8,
    goal: "bajar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Proteína vegetal versátil, baja en calorías.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "lentejas-cocidas",
    name: "Lentejas cocidas",
    kcal: 116,
    proteina: 9,
    carbohidratos: 20,
    grasas: 0.4,
    goal: "mantener",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Proteína vegetal completa con fibra.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "queso-cottage",
    name: "Queso cottage",
    kcal: 98,
    proteina: 11,
    carbohidratos: 3.4,
    grasas: 5,
    goal: "bajar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Proteína láctea magra, excelente para snacks.",
    image: "https://images.unsplash.com/photo-1608272712025-f96be5c0c0e9?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "yogur-griego",
    name: "Yogur griego natural",
    kcal: 100,
    proteina: 10,
    carbohidratos: 6,
    grasas: 5,
    goal: "mantener",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Proteína láctea fermentada con probióticos.",
    image: "https://images.unsplash.com/photo-1585518419759-78ef84c1e6b7?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "yogur-bajo-grasa",
    name: "Yogur bajo en grasa",
    kcal: 59,
    proteina: 10,
    carbohidratos: 3.5,
    grasas: 0.4,
    goal: "bajar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Opción ligera para control de peso.",
    image: "https://images.unsplash.com/photo-1585518419759-78ef84c1e6b7?w=400&h=300&fit=crop",
    type: "proteinas"
  },
  {
    id: "proteina-polvo",
    name: "Proteína en polvo (whey)",
    kcal: 120,
    proteina: 25,
    carbohidratos: 2,
    grasas: 1,
    goal: "bajar",
    category: "Proteína",
    badgeClass: "proteina",
    description: "Suplemento proteico de rápida absorción.",
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&h=300&fit=crop",
    type: "proteinas"
  }
];

// ========================================
// 2. VEGETALES (30+ productos)
// ========================================
const vegetableProducts = [
  {
    id: "espinaca-cruda",
    name: "Espinaca cruda",
    kcal: 23,
    proteina: 2.7,
    carbohidratos: 3.6,
    grasas: 0.4,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Verdura de hoja verde con alto contenido de hierro.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "brocoli",
    name: "Brócoli",
    kcal: 34,
    proteina: 2.8,
    carbohidratos: 7,
    grasas: 0.4,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Crucífera rica en vitamina C y sulforafano.",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "coliflor",
    name: "Coliflor",
    kcal: 25,
    proteina: 1.9,
    carbohidratos: 5,
    grasas: 0.3,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Alternativa baja en carbohidratos a cereales.",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "zanahoria-cruda",
    name: "Zanahoria cruda",
    kcal: 41,
    proteina: 0.9,
    carbohidratos: 10,
    grasas: 0.2,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Rica en betacaroteno, excelente para la vista.",
    image: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "tomate",
    name: "Tomate",
    kcal: 18,
    proteina: 0.9,
    carbohidratos: 3.9,
    grasas: 0.2,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Fuente de licopeno, muy versátil en cocina.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "lechuga-romana",
    name: "Lechuga romana",
    kcal: 15,
    proteina: 1.2,
    carbohidratos: 3,
    grasas: 0.2,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Verdura base para ensaladas, muy ligera.",
    image: "https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "pepino",
    name: "Pepino",
    kcal: 16,
    proteina: 0.7,
    carbohidratos: 3.6,
    grasas: 0.2,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Hortaliza hidratante, casi sin calorías.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "cebolla",
    name: "Cebolla",
    kcal: 40,
    proteina: 1.1,
    carbohidratos: 9,
    grasas: 0.1,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Saborizante bajo en calorías con propiedades antimicrobianas.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "apio",
    name: "Apio",
    kcal: 16,
    proteina: 0.7,
    carbohidratos: 3.7,
    grasas: 0.1,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Verdura refrescante, diurética.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "pimiento-rojo",
    name: "Pimiento rojo",
    kcal: 31,
    proteina: 1,
    carbohidratos: 6,
    grasas: 0.3,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Pimiento dulce rico en vitamina C.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "calabacin",
    name: "Calabacín",
    kcal: 21,
    proteina: 1.5,
    carbohidratos: 3.7,
    grasas: 0.4,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Verdura versátil, base para noodles de verdura.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "champiñones",
    name: "Champiñones",
    kcal: 22,
    proteina: 3.1,
    carbohidratos: 3.3,
    grasas: 0.3,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Hongo comestible con proteína vegetal.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "col",
    name: "Col",
    kcal: 25,
    proteina: 1.3,
    carbohidratos: 5.8,
    grasas: 0.1,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Crucífera versátil para fermentados.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "col-rizada",
    name: "Col rizada (kale)",
    kcal: 49,
    proteina: 4.3,
    carbohidratos: 9,
    grasas: 0.9,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Superalimento con alto contenido nutricional.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "judias-verdes",
    name: "Judías verdes",
    kcal: 31,
    proteina: 1.8,
    carbohidratos: 7,
    grasas: 0.2,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Legumbre tierna, versátil en cocina.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "boniato",
    name: "Boniato",
    kcal: 86,
    proteina: 1.6,
    carbohidratos: 20,
    grasas: 0.1,
    goal: "mantener",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Raíz dulce con beta-caroteno.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "alcachofa",
    name: "Alcachofa",
    kcal: 47,
    proteina: 3.3,
    carbohidratos: 10,
    grasas: 0.1,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Verdura sofisticada con fibra.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "esparragos",
    name: "Espárragos",
    kcal: 20,
    proteina: 2.2,
    carbohidratos: 3.7,
    grasas: 0.1,
    goal: "bajar",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Verdura diurética, excelente en temporada.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  },
  {
    id: "guisantes",
    name: "Guisantes",
    kcal: 81,
    proteina: 5.4,
    carbohidratos: 14,
    grasas: 0.4,
    goal: "mantener",
    category: "Verdura",
    badgeClass: "verdura",
    description: "Legumbre dulce con buen aporte proteico.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "vegetales"
  }
];

// ========================================
// 3. CARBOHIDRATOS (30+ productos)
// ========================================
const carbohydrateProducts = [
  {
    id: "arroz-blanco",
    name: "Arroz blanco cocido",
    kcal: 130,
    proteina: 2.7,
    carbohidratos: 28,
    grasas: 0.3,
    goal: "ganar",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Carbohidrato base, fácil de digerir.",
    image: "https://images.unsplash.com/photo-1555521046-8d1d4ef8cb86?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "arroz-integral",
    name: "Arroz integral cocido",
    kcal: 111,
    proteina: 2.6,
    carbohidratos: 23,
    grasas: 0.9,
    goal: "mantener",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Carbohidrato más nutritivo con fibra.",
    image: "https://images.unsplash.com/photo-1555521046-8d1d4ef8cb86?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "avena",
    name: "Avena cocida",
    kcal: 68,
    proteina: 2.4,
    carbohidratos: 12,
    grasas: 1.4,
    goal: "mantener",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Desayuno saciante con betaglucanos.",
    image: "https://images.unsplash.com/photo-1515182629504-727d7753751f?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "quinua",
    name: "Quinua cocida",
    kcal: 120,
    proteina: 4.4,
    carbohidratos: 21,
    grasas: 1.9,
    goal: "mantener",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Pseudocereal completo con proteína.",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "pasta-cocida",
    name: "Pasta cocida",
    kcal: 131,
    proteina: 4.4,
    carbohidratos: 25,
    grasas: 1.1,
    goal: "ganar",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Carbohidrato versátil y sabroso.",
    image: "https://images.unsplash.com/photo-1473093295203-cad00df16e50?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "pasta-integral",
    name: "Pasta integral cocida",
    kcal: 124,
    proteina: 5.3,
    carbohidratos: 23,
    grasas: 0.9,
    goal: "mantener",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Pasta con más fibra y nutrientes.",
    image: "https://images.unsplash.com/photo-1473093295203-cad00df16e50?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "pan-integral",
    name: "Pan integral",
    kcal: 265,
    proteina: 8.5,
    carbohidratos: 48,
    grasas: 3.3,
    goal: "mantener",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Pan completo con fibra.",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "pan-blanco",
    name: "Pan blanco",
    kcal: 265,
    proteina: 9,
    carbohidratos: 49,
    grasas: 3.2,
    goal: "ganar",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Pan refinado, rápida absorción.",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "papa",
    name: "Papa cocida",
    kcal: 77,
    proteina: 1.7,
    carbohidratos: 17,
    grasas: 0.1,
    goal: "ganar",
    category: "Raíz",
    badgeClass: "cereal",
    description: "Almidón saciante, versátil.",
    image: "https://images.unsplash.com/photo-1596363860436-3b0c8f89c42b?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "camote",
    name: "Camote cocido",
    kcal: 86,
    proteina: 1.6,
    carbohidratos: 20,
    grasas: 0.1,
    goal: "mantener",
    category: "Raíz",
    badgeClass: "cereal",
    description: "Raíz dulce con beta-caroteno.",
    image: "https://images.unsplash.com/photo-1596363860436-3b0c8f89c42b?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "platano-verde",
    name: "Plátano verde cocido",
    kcal: 122,
    proteina: 1.3,
    carbohidratos: 29,
    grasas: 0.3,
    goal: "ganar",
    category: "Raíz",
    badgeClass: "cereal",
    description: "Almidón resistente, saciante.",
    image: "https://images.unsplash.com/photo-1590079876234-8e9b9c9b4b0b?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "granola",
    name: "Granola",
    kcal: 471,
    proteina: 13,
    carbohidratos: 64,
    grasas: 20,
    goal: "ganar",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Mezcla de cereales y frutos secos, muy calórica.",
    image: "https://images.unsplash.com/photo-1515182629504-727d7753751f?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "harina-trigo",
    name: "Harina de trigo (cruda)",
    kcal: 364,
    proteina: 10,
    carbohidratos: 76,
    grasas: 1,
    goal: "ganar",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Base para repostería y cocina.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "harina-integral",
    name: "Harina integral (cruda)",
    kcal: 340,
    proteina: 13,
    carbohidratos: 68,
    grasas: 2,
    goal: "mantener",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Harina con salvado.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "carbohidratos"
  },
  {
    id: "gachas-avena",
    name: "Gachas de avena",
    kcal: 150,
    proteina: 5,
    carbohidratos: 27,
    grasas: 3,
    goal: "mantener",
    category: "Cereal",
    badgeClass: "cereal",
    description: "Desayuno cremoso y saciante.",
    image: "https://images.unsplash.com/photo-1515182629504-727d7753751f?w=400&h=300&fit=crop",
    type: "carbohidratos"
  }
];

// ========================================
// 4. FRUTAS (30+ productos)
// ========================================
const fruitProducts = [
  {
    id: "platano",
    name: "Plátano",
    kcal: 89,
    proteina: 1.1,
    carbohidratos: 23,
    grasas: 0.3,
    goal: "ganar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Fruta energética con potasio.",
    image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "manzana-roja",
    name: "Manzana roja",
    kcal: 52,
    proteina: 0.3,
    carbohidratos: 14,
    grasas: 0.2,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Fruta con pectina, saciante.",
    image: "https://images.unsplash.com/photo-1560806647-a29e4b4b3d36?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "naranja",
    name: "Naranja",
    kcal: 47,
    proteina: 0.9,
    carbohidratos: 12,
    grasas: 0.1,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Cítrica rica en vitamina C.",
    image: "https://images.unsplash.com/photo-1557803104589-90d6d3c2a57a?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "fresa",
    name: "Fresa",
    kcal: 32,
    proteina: 0.8,
    carbohidratos: 7,
    grasas: 0.3,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Baya baja en calorías, antioxidante.",
    image: "https://images.unsplash.com/photo-1464454709131-ffd692591ee5?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "arandano",
    name: "Arándano",
    kcal: 57,
    proteina: 0.7,
    carbohidratos: 14,
    grasas: 0.3,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Superfruta antioxidante.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "kiwi",
    name: "Kiwi",
    kcal: 61,
    proteina: 1.1,
    carbohidratos: 15,
    grasas: 0.5,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Tropical con actinidina digestiva.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "pina",
    name: "Piña",
    kcal: 50,
    proteina: 0.5,
    carbohidratos: 13,
    grasas: 0.1,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Tropical con bromelina.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "mango",
    name: "Mango",
    kcal: 60,
    proteina: 0.8,
    carbohidratos: 15,
    grasas: 0.3,
    goal: "mantener",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Fruta tropical dulce.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "limon",
    name: "Limón",
    kcal: 29,
    proteina: 1.1,
    carbohidratos: 9,
    grasas: 0.3,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Cítrica ácida, muy versátil.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "sandia",
    name: "Sandía",
    kcal: 30,
    proteina: 0.6,
    carbohidratos: 7,
    grasas: 0.2,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Fruta hidratante, muy baja en calorías.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "melon",
    name: "Melón",
    kcal: 34,
    proteina: 0.8,
    carbohidratos: 8,
    grasas: 0.2,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Fruta hidratante, dulce.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "durazno",
    name: "Durazno",
    kcal: 39,
    proteina: 0.9,
    carbohidratos: 10,
    grasas: 0.3,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Fruta de hueso, refrescante.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "pera",
    name: "Pera",
    kcal: 57,
    proteina: 0.4,
    carbohidratos: 15,
    grasas: 0.1,
    goal: "bajar",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Fruta con fibra.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "frutas"
  },
  {
    id: "aguacate-fruta",
    name: "Aguacate",
    kcal: 160,
    proteina: 2,
    carbohidratos: 9,
    grasas: 15,
    goal: "mantener",
    category: "Fruta",
    badgeClass: "fruta",
    description: "Fruta grasa, altamente nutritiva.",
    image: "https://images.unsplash.com/photo-1541614533400-7176038d0d56?w=400&h=300&fit=crop",
    type: "frutas"
  }
];

// ========================================
// 5. GRASAS SALUDABLES (20+ productos)
// ========================================
const fatProducts = [
  {
    id: "aceite-oliva",
    name: "Aceite de oliva",
    kcal: 884,
    proteina: 0,
    carbohidratos: 0,
    grasas: 100,
    goal: "mantener",
    category: "Grasa saludable",
    badgeClass: "grasa",
    description: "Grasa monoinsaturada, antiinflamatoria.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "grasas"
  },
  {
    id: "nueces",
    name: "Nueces",
    kcal: 654,
    proteina: 9.2,
    carbohidratos: 14,
    grasas: 65,
    goal: "mantener",
    category: "Grasa saludable",
    badgeClass: "grasa",
    description: "Semilla con Omega-3.",
    image: "https://images.unsplash.com/photo-1599599810964-d3495da3a440?w=400&h=300&fit=crop",
    type: "grasas"
  },
  {
    id: "almendras",
    name: "Almendras",
    kcal: 579,
    proteina: 21,
    carbohidratos: 22,
    grasas: 50,
    goal: "mantener",
    category: "Grasa saludable",
    badgeClass: "grasa",
    description: "Semilla proteica con vitamina E.",
    image: "https://images.unsplash.com/photo-1599599810964-d3495da3a440?w=400&h=300&fit=crop",
    type: "grasas"
  },
  {
    id: "cacahuetes",
    name: "Cacahuetes",
    kcal: 567,
    proteina: 26,
    carbohidratos: 16,
    grasas: 49,
    goal: "ganar",
    category: "Grasa saludable",
    badgeClass: "grasa",
    description: "Legumbre con proteína.",
    image: "https://images.unsplash.com/photo-1599599810964-d3495da3a440?w=400&h=300&fit=crop",
    type: "grasas"
  },
  {
    id: "avellana",
    name: "Avellanas",
    kcal: 628,
    proteina: 15,
    carbohidratos: 17,
    grasas: 61,
    goal: "mantener",
    category: "Grasa saludable",
    badgeClass: "grasa",
    description: "Semilla con antioxidantes.",
    image: "https://images.unsplash.com/photo-1599599810964-d3495da3a440?w=400&h=300&fit=crop",
    type: "grasas"
  },
  {
    id: "pistacho",
    name: "Pistachos",
    kcal: 557,
    proteina: 20,
    carbohidratos: 28,
    grasas: 45,
    goal: "mantener",
    category: "Grasa saludable",
    badgeClass: "grasa",
    description: "Semilla con luteína.",
    image: "https://images.unsplash.com/photo-1599599810964-d3495da3a440?w=400&h=300&fit=crop",
    type: "grasas"
  },
  {
    id: "semilla-calabaza",
    name: "Semillas de calabaza",
    kcal: 446,
    proteina: 19,
    carbohidratos: 4,
    grasas: 39,
    goal: "mantener",
    category: "Grasa saludable",
    badgeClass: "grasa",
    description: "Semilla con minerales.",
    image: "https://images.unsplash.com/photo-1599599810964-d3495da3a440?w=400&h=300&fit=crop",
    type: "grasas"
  },
  {
    id: "semilla-lino",
    name: "Semillas de lino",
    kcal: 534,
    proteina: 18,
    carbohidratos: 29,
    grasas: 42,
    goal: "mantener",
    category: "Grasa saludable",
    badgeClass: "grasa",
    description: "Semilla con Omega-3.",
    image: "https://images.unsplash.com/photo-1599599810964-d3495da3a440?w=400&h=300&fit=crop",
    type: "grasas"
  },
  {
    id: "semilla-chia",
    name: "Semillas de chía",
    kcal: 486,
    proteina: 17,
    carbohidratos: 42,
    grasas: 31,
    goal: "mantener",
    category: "Grasa saludable",
    badgeClass: "grasa",
    description: "Semilla con fibra y Omega-3.",
    image: "https://images.unsplash.com/photo-1599599810964-d3495da3a440?w=400&h=300&fit=crop",
    type: "grasas"
  },
  {
    id: "mantequilla-almond",
    name: "Mantequilla de almendra",
    kcal: 588,
    proteina: 21,
    carbohidratos: 21,
    grasas: 50,
    goal: "ganar",
    category: "Grasa saludable",
    badgeClass: "grasa",
    description: "Pasta nutritiva.",
    image: "https://images.unsplash.com/photo-1599599810964-d3495da3a440?w=400&h=300&fit=crop",
    type: "grasas"
  }
];

// ========================================
// 6. BEBIDAS (20+ productos)
// ========================================
const beverageProducts = [
  {
    id: "agua",
    name: "Agua",
    kcal: 0,
    proteina: 0,
    carbohidratos: 0,
    grasas: 0,
    goal: "bajar",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Esencial para hidratación, cero calorías.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "cafe-negro",
    name: "Café negro",
    kcal: 2,
    proteina: 0.1,
    carbohidratos: 0,
    grasas: 0,
    goal: "bajar",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Estimulante, prácticamente sin calorías.",
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b3f4?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "cafe-con-leche",
    name: "Café con leche",
    kcal: 40,
    proteina: 2.1,
    carbohidratos: 4.5,
    grasas: 1.7,
    goal: "mantener",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Café con proteína láctea.",
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b3f4?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "te-verde",
    name: "Té verde",
    kcal: 2,
    proteina: 0.4,
    carbohidratos: 0,
    grasas: 0,
    goal: "bajar",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Antioxidante, estimulante leve.",
    image: "https://images.unsplash.com/photo-1597318372603-d2bd8af46e0c?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "zumo-naranja",
    name: "Zumo de naranja",
    kcal: 45,
    proteina: 0.7,
    carbohidratos: 11,
    grasas: 0.2,
    goal: "mantener",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Bebida cítrica natural.",
    image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "licuado-proteico",
    name: "Licuado proteico",
    kcal: 200,
    proteina: 25,
    carbohidratos: 15,
    grasas: 3,
    goal: "bajar",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Bebida proteica casera.",
    image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "batido-frutas",
    name: "Batido de frutas",
    kcal: 120,
    proteina: 3,
    carbohidratos: 25,
    grasas: 0.5,
    goal: "mantener",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Bebida de frutas mezcladas.",
    image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "leche-desnatada",
    name: "Leche desnatada",
    kcal: 35,
    proteina: 3.4,
    carbohidratos: 5,
    grasas: 0.1,
    goal: "bajar",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Leche sin grasa.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "leche-semidesnatada",
    name: "Leche semidesnatada",
    kcal: 49,
    proteina: 3.2,
    carbohidratos: 4.8,
    grasas: 1.7,
    goal: "mantener",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Leche con bajo contenido graso.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "leche-entera",
    name: "Leche entera",
    kcal: 64,
    proteina: 3.2,
    carbohidratos: 4.8,
    grasas: 3.6,
    goal: "ganar",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Leche con contenido graso completo.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "leche-almendra",
    name: "Leche de almendra",
    kcal: 30,
    proteina: 1,
    carbohidratos: 1,
    grasas: 2.5,
    goal: "bajar",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Bebida vegetal baja en calorías.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "bebidas"
  },
  {
    id: "leche-soja",
    name: "Leche de soja",
    kcal: 33,
    proteina: 3.3,
    carbohidratos: 1.3,
    grasas: 1.8,
    goal: "bajar",
    category: "Bebida",
    badgeClass: "bebida",
    description: "Bebida vegetal proteica.",
    image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd13352?w=400&h=300&fit=crop",
    type: "bebidas"
  }
];

// ========================================
// BASE DE DATOS COMPLETA CENTRALIZADA
// ========================================
window.foodDatabase = [
  ...proteinProducts,
  ...vegetableProducts,
  ...carbohydrateProducts,
  ...fruitProducts,
  ...fatProducts,
  ...beverageProducts
];

console.log(`✅ NutriFit Database Loaded: ${window.foodDatabase.length} productos`);
